# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/ECT-UA/CR/Nexys4_Master.xdc

# Block Designs: bd/hardversion/hardversion.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion || ORIG_REF_NAME==hardversion}]

# IP: bd/hardversion/ip/hardversion_blk_mem_gen_0_0/hardversion_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_blk_mem_gen_0_0 || ORIG_REF_NAME==hardversion_blk_mem_gen_0_0}]

# IP: bd/hardversion/ip/hardversion_clock_divider_0_0/hardversion_clock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_clock_divider_0_0 || ORIG_REF_NAME==hardversion_clock_divider_0_0}]

# IP: bd/hardversion/ip/hardversion_DC32_0_0/hardversion_DC32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_DC32_0_0 || ORIG_REF_NAME==hardversion_DC32_0_0}]

# IP: bd/hardversion/ip/hardversion_unroll_0_0/hardversion_unroll_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_unroll_0_0 || ORIG_REF_NAME==hardversion_unroll_0_0}]

# IP: bd/hardversion/ip/hardversion_imparE_0_0/hardversion_imparE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_imparE_0_0 || ORIG_REF_NAME==hardversion_imparE_0_0}]

# IP: bd/hardversion/ip/hardversion_xlconcat_0_0/hardversion_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_xlconcat_0_0 || ORIG_REF_NAME==hardversion_xlconcat_0_0}]

# IP: bd/hardversion/ip/hardversion_xlconcat_1_0/hardversion_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_xlconcat_1_0 || ORIG_REF_NAME==hardversion_xlconcat_1_0}]

# IP: bd/hardversion/ip/hardversion_xlconstant_0_1/hardversion_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_xlconstant_0_1 || ORIG_REF_NAME==hardversion_xlconstant_0_1}]

# IP: bd/hardversion/ip/hardversion_sendImpar_0_0/hardversion_sendImpar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hardversion_sendImpar_0_0 || ORIG_REF_NAME==hardversion_sendImpar_0_0}]

# XDC: bd/hardversion/ip/hardversion_blk_mem_gen_0_0/hardversion_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/hardversion/ip/hardversion_unroll_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardversion_unroll_0_0 || ORIG_REF_NAME==hardversion_unroll_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hardversion/ip/hardversion_imparE_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardversion_imparE_0_0 || ORIG_REF_NAME==hardversion_imparE_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hardversion/ip/hardversion_sendImpar_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hardversion_sendImpar_0_0 || ORIG_REF_NAME==hardversion_sendImpar_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hardversion/hardversion_ooc.xdc
