# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/ECT-UA/CR/Nexys4_Master.xdc

# Block Designs: bd/MB_version/MB_version.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version || ORIG_REF_NAME==MB_version}]

# IP: bd/MB_version/ip/MB_version_microblaze_0_0/MB_version_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_microblaze_0_0 || ORIG_REF_NAME==MB_version_microblaze_0_0}]

# IP: bd/MB_version/ip/MB_version_dlmb_v10_0/MB_version_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_dlmb_v10_0 || ORIG_REF_NAME==MB_version_dlmb_v10_0}]

# IP: bd/MB_version/ip/MB_version_ilmb_v10_0/MB_version_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_ilmb_v10_0 || ORIG_REF_NAME==MB_version_ilmb_v10_0}]

# IP: bd/MB_version/ip/MB_version_dlmb_bram_if_cntlr_0/MB_version_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_version_dlmb_bram_if_cntlr_0}]

# IP: bd/MB_version/ip/MB_version_ilmb_bram_if_cntlr_0/MB_version_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_version_ilmb_bram_if_cntlr_0}]

# IP: bd/MB_version/ip/MB_version_lmb_bram_0/MB_version_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_lmb_bram_0 || ORIG_REF_NAME==MB_version_lmb_bram_0}]

# IP: bd/MB_version/ip/MB_version_microblaze_0_axi_periph_0/MB_version_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_version_microblaze_0_axi_periph_0}]

# IP: bd/MB_version/ip/MB_version_mdm_1_0/MB_version_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_mdm_1_0 || ORIG_REF_NAME==MB_version_mdm_1_0}]

# IP: bd/MB_version/ip/MB_version_clk_wiz_1_0/MB_version_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_clk_wiz_1_0 || ORIG_REF_NAME==MB_version_clk_wiz_1_0}]

# IP: bd/MB_version/ip/MB_version_rst_clk_wiz_1_100M_0/MB_version_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_version_rst_clk_wiz_1_100M_0}]

# IP: bd/MB_version/ip/MB_version_blk_mem_gen_0_0/MB_version_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_blk_mem_gen_0_0 || ORIG_REF_NAME==MB_version_blk_mem_gen_0_0}]

# IP: bd/MB_version/ip/MB_version_axi_gpio_0_0/MB_version_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_axi_gpio_0_0 || ORIG_REF_NAME==MB_version_axi_gpio_0_0}]

# IP: bd/MB_version/ip/MB_version_xbar_0/MB_version_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_xbar_0 || ORIG_REF_NAME==MB_version_xbar_0}]

# IP: bd/MB_version/ip/MB_version_xlslice_0_0/MB_version_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_xlslice_0_0 || ORIG_REF_NAME==MB_version_xlslice_0_0}]

# IP: bd/MB_version/ip/MB_version_xlslice_1_0/MB_version_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_xlslice_1_0 || ORIG_REF_NAME==MB_version_xlslice_1_0}]

# IP: bd/MB_version/ip/MB_version_xlconstant_0_0/MB_version_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_xlconstant_0_0 || ORIG_REF_NAME==MB_version_xlconstant_0_0}]

# IP: bd/MB_version/ip/MB_version_xlconstant_1_0/MB_version_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_xlconstant_1_0 || ORIG_REF_NAME==MB_version_xlconstant_1_0}]

# IP: bd/MB_version/ip/MB_version_unroll_0_0/MB_version_unroll_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_unroll_0_0 || ORIG_REF_NAME==MB_version_unroll_0_0}]

# IP: bd/MB_version/ip/MB_version_imparE_0_0/MB_version_imparE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_imparE_0_0 || ORIG_REF_NAME==MB_version_imparE_0_0}]

# IP: bd/MB_version/ip/MB_version_sendImpar_0_0/MB_version_sendImpar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_sendImpar_0_0 || ORIG_REF_NAME==MB_version_sendImpar_0_0}]

# IP: bd/MB_version/ip/MB_version_clock_divider_0_0/MB_version_clock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_clock_divider_0_0 || ORIG_REF_NAME==MB_version_clock_divider_0_0}]

# IP: bd/MB_version/ip/MB_version_DC32_0_0/MB_version_DC32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_DC32_0_0 || ORIG_REF_NAME==MB_version_DC32_0_0}]

# IP: bd/MB_version/ip/MB_version_xlconcat_0_0/MB_version_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_xlconcat_0_0 || ORIG_REF_NAME==MB_version_xlconcat_0_0}]

# IP: bd/MB_version/ip/MB_version_xlconcat_1_0/MB_version_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_xlconcat_1_0 || ORIG_REF_NAME==MB_version_xlconcat_1_0}]

# IP: bd/MB_version/ip/MB_version_xlconstant_3_0/MB_version_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_xlconstant_3_0 || ORIG_REF_NAME==MB_version_xlconstant_3_0}]

# IP: bd/MB_version/ip/MB_version_auto_pc_0/MB_version_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_auto_pc_0 || ORIG_REF_NAME==MB_version_auto_pc_0}]

# IP: bd/MB_version/ip/MB_version_auto_pc_1/MB_version_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_auto_pc_1 || ORIG_REF_NAME==MB_version_auto_pc_1}]

# XDC: bd/MB_version/ip/MB_version_microblaze_0_0/MB_version_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_microblaze_0_0 || ORIG_REF_NAME==MB_version_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_microblaze_0_0/MB_version_microblaze_0_0_ooc_debug.xdc

# XDC: bd/MB_version/ip/MB_version_microblaze_0_0/MB_version_microblaze_0_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_dlmb_v10_0/MB_version_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_dlmb_v10_0 || ORIG_REF_NAME==MB_version_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_dlmb_v10_0/MB_version_dlmb_v10_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_ilmb_v10_0/MB_version_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_ilmb_v10_0 || ORIG_REF_NAME==MB_version_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_ilmb_v10_0/MB_version_ilmb_v10_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_dlmb_bram_if_cntlr_0/MB_version_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_ilmb_bram_if_cntlr_0/MB_version_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_lmb_bram_0/MB_version_lmb_bram_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_mdm_1_0/MB_version_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_mdm_1_0 || ORIG_REF_NAME==MB_version_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_mdm_1_0/MB_version_mdm_1_0_ooc_trace.xdc

# XDC: bd/MB_version/ip/MB_version_mdm_1_0/MB_version_mdm_1_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_clk_wiz_1_0/MB_version_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_clk_wiz_1_0 || ORIG_REF_NAME==MB_version_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/MB_version/ip/MB_version_clk_wiz_1_0/MB_version_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_clk_wiz_1_0 || ORIG_REF_NAME==MB_version_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/MB_version/ip/MB_version_clk_wiz_1_0/MB_version_clk_wiz_1_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_rst_clk_wiz_1_100M_0/MB_version_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_version_rst_clk_wiz_1_100M_0}]

# XDC: bd/MB_version/ip/MB_version_rst_clk_wiz_1_100M_0/MB_version_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_version_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_version_rst_clk_wiz_1_100M_0}]

# XDC: bd/MB_version/ip/MB_version_rst_clk_wiz_1_100M_0/MB_version_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_blk_mem_gen_0_0/MB_version_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_axi_gpio_0_0/MB_version_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_axi_gpio_0_0 || ORIG_REF_NAME==MB_version_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_axi_gpio_0_0/MB_version_axi_gpio_0_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_axi_gpio_0_0/MB_version_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_axi_gpio_0_0 || ORIG_REF_NAME==MB_version_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_xbar_0/MB_version_xbar_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_unroll_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_unroll_0_0 || ORIG_REF_NAME==MB_version_unroll_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_imparE_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_imparE_0_0 || ORIG_REF_NAME==MB_version_imparE_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_sendImpar_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MB_version_sendImpar_0_0 || ORIG_REF_NAME==MB_version_sendImpar_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MB_version/ip/MB_version_auto_pc_0/MB_version_auto_pc_0_ooc.xdc

# XDC: bd/MB_version/ip/MB_version_auto_pc_1/MB_version_auto_pc_1_ooc.xdc

# XDC: bd/MB_version/MB_version_ooc.xdc
