# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.cache/wt [current_project]
set_property parent.project_path D:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  d:/ECT-UA/CR
  d:/ECT-UA/CR/tarefa19_1/unroll
  d:/ECT-UA/CR/tarefa19_1/clockDivider
  d:/ECT-UA/CR/tarefa19_1/imparE
  d:/ECT-UA/CR/tarefa19_1/sendImpar
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files D:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/MB_version.bd
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_microblaze_0_0/MB_version_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_microblaze_0_0/MB_version_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_microblaze_0_0/MB_version_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_dlmb_v10_0/MB_version_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_dlmb_v10_0/MB_version_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_ilmb_v10_0/MB_version_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_ilmb_v10_0/MB_version_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_dlmb_bram_if_cntlr_0/MB_version_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_ilmb_bram_if_cntlr_0/MB_version_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_lmb_bram_0/MB_version_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_mdm_1_0/MB_version_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_mdm_1_0/MB_version_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_mdm_1_0/MB_version_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_clk_wiz_1_0/MB_version_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_clk_wiz_1_0/MB_version_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_clk_wiz_1_0/MB_version_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_rst_clk_wiz_1_100M_0/MB_version_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_rst_clk_wiz_1_100M_0/MB_version_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_rst_clk_wiz_1_100M_0/MB_version_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_blk_mem_gen_0_0/MB_version_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_axi_gpio_0_0/MB_version_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_axi_gpio_0_0/MB_version_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_axi_gpio_0_0/MB_version_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_xbar_0/MB_version_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_unroll_0_0/src/Nexys4_Master.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_imparE_0_0/src/Nexys4_Master.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_sendImpar_0_0/src/Nexys4_Master.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_auto_pc_0/MB_version_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/ip/MB_version_auto_pc_1/MB_version_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/MB_version_ooc.xdc]
set_property is_locked true [get_files D:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/MB_version.bd]

read_vhdl -library xil_defaultlib D:/ECT-UA/CR/tarefa19_1/SoftVersion/SoftVersion.srcs/sources_1/bd/MB_version/hdl/MB_version_wrapper.vhd
read_xdc D:/ECT-UA/CR/Nexys4_Master.xdc
set_property used_in_implementation false [get_files D:/ECT-UA/CR/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top MB_version_wrapper -part xc7a100tcsg324-2
write_checkpoint -noxdef MB_version_wrapper.dcp
catch { report_utilization -file MB_version_wrapper_utilization_synth.rpt -pb MB_version_wrapper_utilization_synth.pb }
