# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/ECT-UA/CR/tarefa19_1/sendImpar/sendImpar.cache/wt [current_project]
set_property parent.project_path D:/ECT-UA/CR/tarefa19_1/sendImpar/sendImpar.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths d:/ect-ua/cr/tarefa19_1/sendimpar [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib D:/ECT-UA/CR/tarefa19_1/sendImpar/sendImpar.srcs/sources_1/new/sendImpar.vhd
read_xdc D:/ECT-UA/CR/Nexys4_Master.xdc
set_property used_in_implementation false [get_files D:/ECT-UA/CR/Nexys4_Master.xdc]

synth_design -top sendImpar -part xc7a100tcsg324-3
write_checkpoint -noxdef sendImpar.dcp
catch { report_utilization -file sendImpar_utilization_synth.rpt -pb sendImpar_utilization_synth.pb }
